# Generated by Django 4.2.4 on 2023-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='site_icon',
        ),
        migrations.AddField(
            model_name='info',
            name='avatar',
            field=models.ImageField(default='asdf', upload_to='.media/avatars', verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
