# Generated by Django 4.2.4 on 2023-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_info_site_icon_info_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('logo', models.ImageField(upload_to='.media/logos', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Is Checked?'),
        ),
    ]
