# Generated by Django 5.0.1 on 2024-01-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='avatar',
            field=models.ImageField(upload_to='media/avatars', verbose_name='Avatar'),
        ),
    ]
