# Generated by Django 5.0.1 on 2024-01-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_client_logo_alter_info_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddField(
            model_name='info',
            name='about',
            field=models.TextField(default='a', verbose_name='About Me'),
            preserve_default=False,
        ),
    ]
