# Generated by Django 5.0.1 on 2024-01-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_delete_about_info_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_name',
            field=models.CharField(default='design', max_length=10, verbose_name='Icon Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='short_text',
            field=models.CharField(default='Design Short Text', max_length=200, verbose_name='Short Text'),
            preserve_default=False,
        ),
    ]
