# Generated by Django 5.0.1 on 2024-01-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_skill_icon_name_skill_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='avatar',
            field=models.ImageField(null=True, upload_to='./avatars', verbose_name='Avatar'),
        ),
    ]
