# Generated by Django 5.0.1 on 2024-01-13 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_message_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of create'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='./avatars', verbose_name='Avatar'),
        ),
    ]
