# Generated by Django 5.0.1 on 2024-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_message_created_at_alter_message_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='./avatars', verbose_name='Avatar'),
        ),
    ]
