# Generated by Django 5.0.1 on 2024-01-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_message_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(default='https://centr-jalyuzi.uz/', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
