# Generated by Django 5.0.1 on 2024-01-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_resume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Alias'),
            preserve_default=False,
        ),
    ]
