# Generated by Django 5.0.1 on 2024-01-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_rename_created_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='location_url',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1281.226342897437!2d67.0058682988049!3d39.65824051580189!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sru!2s!4v1705143352603!5m2!1sru!2s', verbose_name='Location URL'),
            preserve_default=False,
        ),
    ]
