# Generated by Django 5.0.1 on 2024-01-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_remove_message_phone_message_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='birthday',
            field=models.DateTimeField(verbose_name='Birthday'),
        ),
    ]
