# Generated by Django 5.0.1 on 2024-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_alter_info_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.FileField(default='media/skills_icon/icon.svg', upload_to='./skills_icon', verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
