# Generated by Django 5.0.1 on 2024-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_remove_skill_icon_name_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='period',
            field=models.CharField(max_length=20, verbose_name='Time Period'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.FileField(upload_to='./icons', verbose_name='Icon'),
        ),
    ]
