# Generated by Django 5.0.1 on 2024-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_alter_resume_period_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
