# Generated by Django 5.0.1 on 2024-01-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_resume_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Order'),
        ),
    ]
