# Generated by Django 5.0.1 on 2024-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_alter_resume_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=46, verbose_name='Bot Token')),
                ('chat_id', models.CharField(max_length=15, verbose_name='Chat ID')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['order'], 'verbose_name': 'Resume', 'verbose_name_plural': 'Resume'},
        ),
    ]
